### ISSUE TITLE
Add sourcemaps to debug typescript in browser or import typescript.js to run In runtime

### ISSUE THREAD

**Issue by danicomas** [driftyco/ionic2-starter#20]
Other thing which is the current ionic2-starter this project or https://github.com/driftyco/ionic2-starter-tutorial?

**Comment by PaulWasilewski** [comment]
To activate sourcemaps just add following lines under `module.exports` to your `webpack.config.js`.

    debug: true,
    devtool: 'source-map',

Also make sure your `tsconfig.json` contains

    "sourceMap": true,

Happy debugging :)

**Comment by mhartington** [comment]
So this repo is no long usable with the current CLI and should not be used anymore. Please follow the instructions for creating new projects using the CLI

http://ionicframework.com/docs/v2/getting-started/installation/
