### ISSUE TITLE
Compiling ts files

### ISSUE THREAD

**Issue by robyedlin** [driftyco/ionic2-starter#21]
In the www folder, when I make a change to the data.ts file, I'm not sure how to compile that to the data.js file and rebuild the build/js/app.bundle.js file.

Am I missing something here?

**Comment by mhartington** [comment]
So this repo is no long usable with the current CLI and should not be used anymore. Please follow the instructions for creating new projects using the CLI

http://ionicframework.com/docs/v2/getting-started/installation/
