### ISSUE TITLE
not working out of the box

### ISSUE THREAD

**Issue by talarari** [driftyco/ionic2-starter#22]
cloned, ran npm install and gulp serve , getting a blank page with these errors in console:
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/cordova.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/js/app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/css/app.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by erichiggins** [comment]
I had the same problem. There are two things missing:

1) Their `package.json` doesn't declare `gulp-cli` as a dependency to install (but it looks like you already have this).
2) The `gulp serve` command depends on files generated by the `gulp build` task. If you run that, then run `gulp serve`, the page should render.

**Comment by mhartington** [comment]
So this repo is no long usable with the current CLI and should not be used anymore. Please follow the instructions for creating new projects using the CLI

http://ionicframework.com/docs/v2/getting-started/installation/
