### ISSUE TITLE
not running out of the box

### ISSUE THREAD

**Issue by cosmaioan** [driftyco/ionic2-starter#23]
Did a git clone of this repo (cb8252896ef8cbee36ae9dbfbd9506ab51ce21b9)
Enviropnment: Microsoft Windows [Version 10.0.10586], node v4.0.0 npm 3.5.0
executed 
npm install. (npm 3.5.0)
gulp build => errors bellow
`
ERROR in multi main
Module not found: Error: Cannot resolve module 'web-animations.min' in C:\cid\projects\learn123\p1\i
onic2-starter
 @ multi main

ERROR in ./www/app/app.js
Module build failed: Cannot resolve module 'ionic/ionic' in C:\cid\projects\learn123\p1\ionic2-start
er\www\app
    Required in C:\cid\projects\learn123\p1\ionic2-starter\www\app\app.js
 @ multi main
`

**Comment by cosmaioan** [comment]
this is specific to alpha 35.36. Works with alha 30

**Comment by voycey** [comment]
Im on Alpha 30 and I am having this same problem

**Comment by lordgreg** [comment]
This bug is still present and I can't do or test a thing.

```

ERROR in multi main
Module not found: Error: Cannot resolve module 'web-animations.min' in C:\Development\ionic2-starter
 @ multi main

ERROR in ./www/app/app.js
Module build failed: Cannot resolve module 'ionic/ionic' in C:\Development\ionic2-starter\www\app
    Required in C:\Development\ionic2-starter\www\app\app.js
 @ multi main
```

or in browser:
```
GET http://localhost:8100/build/css/app.css 
GET http://localhost:8100/cordova.js 
Uncaught Error: Cannot find module "web-animations.min"webpackMissingModule @ app.bundle.js:50(anonymous function) @ app.bundle.js:50__webpack_require__ @ app.bundle.js:20(anonymous function) @ app.bundle.js:40(anonymous function) @ app.bundle.js:43
```

**Comment by lordgreg** [comment]
Any help we can get on this problem? I've also tried to update dependency for ionic-framework to v40, 35, 30... nothing helped.

**Comment by mhartington** [comment]
Hey all, sorry about the delay. So this repo is no long usable with the current CLI and should not be used anymore. Please follow the instructions for creating new projects using the CLI

http://ionicframework.com/docs/v2/getting-started/installation/
