### ISSUE TITLE
project don't start

### ISSUE THREAD

**Issue by victorcarvalhosp** [driftyco/ionic2-starter#24]
I followed the steps:
Clone repo
npm install
gulp serve

But the result is a blank screen and the erros in console:
(index):7 GET http://localhost:8101/build/css/app.css 

(index):16 GET http://localhost:8101/cordova.js 

(index):17 GET http://localhost:8101/build/js/app.bundle.js 

I did something wrong?

**Comment by kittencup** [comment]
me too....

**Comment by mhartington** [comment]
So this repo is no long usable with the current CLI and should not be used anymore. Please follow the instructions for creating new projects using the CLI

http://ionicframework.com/docs/v2/getting-started/installation/
