### ISSUE TITLE
Change .js extension in www to .ts

### ISSUE THREAD

**Issue by tobiasmuecksch** [driftyco/ionic2-starter#25]
Like discussed [here](https://github.com/driftyco/ionic2/issues/527) it's confusing that the typescript files have javascript extension.

I hereby request that starter to rely on the true TypeScript File Extension in order to improve convenience.

Just to mention it: IDEs like WebStorm are confused as hell. Changing the JS mode to ES6 helps a little but disables the TypeScript specific features the IDE offers.

**Comment by mhartington** [comment]
So this repo is no long usable with the current CLI and should not be used anymore. Please follow the instructions for creating new projects using the CLI

http://ionicframework.com/docs/v2/getting-started/installation/
